services:
  backend:
    build: .
    env_file:
      ../.env
    image: us-east1-docker.pkg.dev/$PROJECT_ID/buckcat-registry/buckcat-backend:latest
    secrets:
      - gcloud_credentials
    

secrets:
  gcloud_credentials:
    file: $GOOGLE_APPLICATION_CREDENTIALS_FILE
