services:
  backend:
    build: .
    image: us-east1-docker.pkg.dev/prefab-lamp-440513-v5/buckcat-registry/buckcat-backend:latest
    secrets:
      - gcloud_credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcloud_credentials

secrets:
  gcloud_credentials:
    file: ../.gcp-service-account-credentials.json
