name: Deploy Latest Frontend Image Into GCI

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Build and Push Frontend Image to GAR"]
    types:
    - completed

env:
  GCP_REGION: us-east1
  INSTANCE: buckcat-frontend-instance
  PROJECT_ID: ${{secrets.PROJECT_ID}}

jobs:
  Deploy_Frontend_to_GCI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: projects/765231548917/locations/global/workloadIdentityPools/buckcat-workload-identity-pool/providers/buckcat-github
          service_account: ${{secrets.SERVICE_ACCOUNT_MAIL}}
      - 
        name: SSH and Update Container
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        env:
          ZONE: ${{env.GCP_REGION}}-b
        with:
          instance_name: ${{env.INSTANCE}}
          zone: ${{env.ZONE}}
          ssh_private_key: '${{secrets.FRONTEND_SSH_KEY}}'
          command: |
            sudo docker stop $(docker ps -q)
            sudo docker container prune -f
            sudo docker image prune -a -f
            sudo docker-credential-gcr configure-docker --registries=us-east1-docker.pkg.dev
            sudo docker run -d -p 80:80 us-east1-docker.pkg.dev/${{env.PROJECT_ID}}/buckcat-registry/buckcat-frontend:latest
