name: Build and Push Frontend Image to GAR

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Frontend/**

env:
  GCP_REGION: us-east1

jobs:
  Build_and_Push_Frontend_to_GAR:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: projects/765231548917/locations/global/workloadIdentityPools/buckcat-workload-identity-pool/providers/buckcat-github
          service_account: ${{secrets.SERVICE_ACCOUNT_MAIL}}
      -
        name: Login to GAR
        id: gar-login
        uses: docker/login-action@v3
        with:
          registry: ${{env.GCP_REGION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{steps.gcp-auth.outputs.access_token}}
      -
        name: Build and Push Frontend Container Image
        id: build-frontend-image
        env:
          COMPOSE_FILE: ./Frontend/compose.yaml
          PROJECT_ID: ${{secrets.PROJECT_ID}}
        run: |
          docker compose -f $COMPOSE_FILE build
          docker compose push
