name: Build and Push Image to GAR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
      - feature/cicd
    paths:
      - .github/workflows/ci-pipeline.yaml

env:
  GCP_REGION: us-east1

jobs:
  Build_and_Push_Frontend_to_GAR:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -  
        name: Authenticate and Login
        uses: ./.github/workflows/gcp-and-docker-auth.yaml
        with:
          gcp_region: ${{env.GCP_REGION}}
          service_account_mail: ${{secrets.SERVICE_ACCOUNT_MAIL}}
      -
        name: Build and Push Frontend Container Image
        id: build-frontend-image
        env:
          COMPOSE_FILE: ./Frontend/compose.yaml
          PROJECT_ID: ${{secrets.PROJECT_ID}}
        run: |
          docker compose -f $COMPOSE_FILE build
          docker compose push
  
  Build_and_Push_Backend_to_GAR:
    runs-on: ubuntu-latest
    steps:
      -  
        name: Authenticate and Login
        uses: ./.github/workflows/gcp-and-docker-auth.yaml
        with:
          gcp_region: ${{env.GCP_REGION}}
          service_account_mail: ${{secrets.SERVICE_ACCOUNT_MAIL}}
      -
        name: Build and Push Backend Container Image
        id: build-frontend-image
        env:
          COMPOSE_FILE: ./Backend/compose.yaml
          PROJECT_ID: ${{secrets.PROJECT_ID}}
        run: |
          docker compose -f $COMPOSE_FILE build
          docker compose push
