name: Authenticate and Login to GAR

on:
  workflow_call:
    inputs:
      gcp_region:
        required: true
        type: string
      service_account_mail:
        required: true
        type: string

jobs:
    authenticate_and_login:
        runs-on: ubuntu-latest
        outputs:
            access_token: ${{ steps.gcp-auth.outputs.access_token }}
        steps:
        -
          name: Authenticate to GCP
          id: gcp-auth
          uses: google-github-actions/auth@v2
          with:
              create_credentials_file: true
              token_format: access_token
              workload_identity_provider: projects/765231548917/locations/global/workloadIdentityPools/buckcat-workload-identity-pool/providers/buckcat-github
              service_account: ${{ inputs.service_account_mail }}
        -
          name: Login to GAR
          id: gar-login
          uses: docker/login-action@v3
          with:
              registry: ${{ inputs.gcp_region }}-docker.pkg.dev
              username: oauth2accesstoken
              password: ${{ steps.gcp-auth.outputs.access_token }}
